Areas/Admin/Controllers/NewArticleController.cs
using NAVY4U.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TheFourthPractice.Areas.Admin.Controllers
{
    public class NewArticleController : Controller
    {
        private static BanHangOnlineEntities database = new BanHangOnlineEntities();
        // GET: Admin/NewArticle
        public ActionResult Index()
        {
            return View();
        }

    }
}

Areas/Admin/Views/NewArticle/Index.cshtml
@model NAVY4U.Models.baiViet
@{
    ViewBag.Title = "New Article";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Bài viết mới</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index", "Dashboard")">Home</a>
                    </li>
                    <li class="breadcrumb-item active">New Article</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="container-fluid">
    @using (Html.BeginForm("Index", "NewArticle", FormMethod.Post))
    {
        <div class="row">
            <!-- left column -->
            <div class="col-sm-8">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Thông tin chính</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="tenbaiviet">Tên bài viết</label>
                                <input type="text" class="form-control" id="tenbaiviet" placeholder="Tên bài viết tối đa 50 ký tự">
                            </div>
                            <div class="form-group">
                                <label for="noidungtt">Nội dung tóm tắt</label>
                                <textarea rows="5" class="form-control" placeholder="Nội dung tối đa 150 từ"></textarea>
                            </div>
                        </div>
                    </form>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- right column -->
            <div class="col-sm-4">
                <div class="card card-warning">
                    <div class="card-header">
                        <h3 class="card-title">Ảnh </h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <label for="exampleInputFile">File input</label>
                        <div class="col-sm-12 pb-3">
                            <img class="w-100" src="~/Images/news/2.png" />
                        </div>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="exampleInputFile">
                                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                            </div>
                            <div class="input-group-append">
                                <span class="input-group-text" id="">Upload</span>
                            </div>
                        </div>
                    </div>
                </div>
                <!--/.col (right) -->
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Đăng tải bài viết</button>
            </div>
        </div>
    }
</div>